# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b32b5403c73f358df484a6bead5f833"
name = "tiered-discount-function"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts,read_discounts,write_files,read_files,write_publications,read_publications,write_inventory,read_locations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
